name: Angular CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Download build
          uses: actions/download-artifact@v1
          with:
            name: deploy_dist
        - name: 'Authenticate GCP'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'projects/796408276927/locations/global/workloadIdentityPools/waitlist-identity-pool/providers/github-provider'
            service_account: 'deployment-service-account@waitlist-384622.iam.gserviceaccount.com'
        - name: 'Deploy to Storage'
          uses: 'google-github-actions/upload-cloud-storage@v1'
          with:
            path: 'deploy_dist/library-waitlist'
            destination: 'library-app'
            parent: false
